### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/trit-school-1#7]
Read about "github pages". Create the required branch and push here only required code (it's kind of production code).

Read about it. But I can create a github page only in my repository, not yours. Or maybe I'm wrong?
Made a new branch "picture-gallery"

**Comment by tritonJS826** [comment]
Gh-pages created. Feel free to use it)

**Comment by Ekaterina1994** [comment]
Give me a task for gh pages.

**Comment by Ekaterina1994** [comment]
My new links on new pages don't work. I think it because folders with code should be on brunch gh-pages. So should I create all code here?

**Comment by tritonJS826** [comment]
Not all, only build! But its the right way) (hope "here" mean gh-pages)

**Comment by Ekaterina1994** [comment]
Done
